apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: CI
  name: cv-ci
spec:
  replicas: 1
  selector:
    app: CI
    deploymentconfig: cv-ci
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: CI
        deploymentconfig: cv-ci
    spec:
      containers:
        - env:
          - name: PORT
            value: '4000'
          - name: APM_SERVER
            value: 'https://f7a3f8bb7ac7404eb669a8798e460701.apm.eu-west-1.aws.cloud.es.io:443'
          - name: APM_TOKEN
            valueFrom:
              secretKeyRef:
                name: apm
                key: token
          - name: APP_NAME
            value: mydata-cv api
          - name: NODE_ENV
            value: test
          - name: OPERATOR_URL
            value: 'http://operator-ci.mydata.svc:3000'
          - name: POSTGRES_USER
            value: postgresuser
          - name: POSTGRES_PASSWORD
            value: postgrespassword
          - name: POSTGRES_DB
            value: cv
          - name: DATABASE_URL
            value: postgres://postgresuser:postgrespassword@postgresql-cv-ci.mydata.svc:5432/cv
          - name: REDIS
            value: 'redis://:fubar@redis-ci.mydata.svc:6379/'
          - name: CLIENT_ID
            value: https://cv-ci.dev.services.jtech.se
          - name: NO_UPDATE_NOTIFIER
            value: 'true'
          - name: PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                name: cv
                key: public.key
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: cv
                key: private.key
          image: cv:latest
          imagePullPolicy: Always
          name: cv-ci
          ports:
            - containerPort: 4000
              name: http
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              memory: 400Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - cv-ci
        from:
          kind: ImageStreamTag
          name: cv:latest
      type: ImageChange
