apiVersion: v1
kind: Service
metadata:
  labels:
    app: CI
  name: redis-ci
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis-ci
  sessionAffinity: None
  type: ClusterIP
