apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: cv
spec:
  tags:
    # Latest, for CI
    - name: latest
      referencePolicy:
        type: Source
    # Test
    - name: test
      referencePolicy:
        type: Source
