apiVersion: v1
kind: Service
metadata:
  name: postgresql-cv-ci
  labels:
    app: CI
spec:
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgresql-cv-ci
  sessionAffinity: None
  type: ClusterIP
