apiVersion: v1
kind: Service
metadata:
  labels:
    app: TEST
  name: redis-test
spec:
  ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    name: redis-test
  sessionAffinity: None
  type: ClusterIP
