apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: operator
spec:
  tags:
    # Latest, for CI
    - name: latest
      referencePolicy:
        type: Source
    # Test
    - name: test
      referencePolicy:
        type: Source
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: operator-ci
spec:
  runPolicy: Serial
  triggers:
    -
      type: GitHub
      github:
        secretReference:
          name: github-webhook-secret
  source:
    git:
      ref: master
      uri: https://github.com/jobtechswe/mydata
    contextDir: operator
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: operator:latest
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: operator-test
spec:
  runPolicy: Serial
  source:
    git:
      ref: v0.0.1
      uri: https://github.com/jobtechswe/mydata
    contextDir: operator
  strategy:
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: operator:test
