#!/bin/bash

TAG="$1"
git tag "$TAG"
git push origin "$TAG"

oc patch buildconfig cv-test -p '{"spec": {"source": {"git": {"ref": "'$TAG'"}}}}'
oc patch buildconfig operator-test -p '{"spec": {"source": {"git": {"ref": "'$TAG'"}}}}'

oc start-build cv-test -n mydata
oc start-build operator-test -n mydata
